declare module 'bun' {
	interface Env {
		PAPERLESS_URL: string;
		PAPERLESS_TOKEN: string;
		DOCLING_URL?: string;
		LLM_ANSWER_LANGUAGE?: string;
		OWN_NAME?: string;

		OPENAI_COMPATIBLE_API_URL: string;
		OPENAI_COMPATIBLE_API_KEY?: string;
		OPENAI_COMPATIBLE_MODEL: string;
		OPENAI_COMPATIBLE_VISION?: string;

		OPENAI_COMPATIBLE_SECONDARY_API_URL?: string;
		OPENAI_COMPATIBLE_SECONDARY_API_KEY?: string;
		OPENAI_COMPATIBLE_SECONDARY_MODEL?: string;
		OPENAI_COMPATIBLE_SECONDARY_VISION?: string;

		POLL_INTERVAL_MS?: string;
		TAG_AI_AUTO?: string;
		TAG_AI_OCR_AUTO?: string;
		TAG_AI_OCR_DONE?: string;
		TAG_AI_DONE?: string;
		TAG_AI_FAILED?: string;
		OCR_MODE?: string;
		OCR_MIN_CHARS_PER_PAGE?: string;
		ALLOW_NEW_CORRESPONDENT?: string;
	}
}
